[project]

name = "pjpipe"
version = "1.3.0"
description = "JWST Pipeline Wrapper for Nearby Galaxies"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}

authors = [
    {name = "Thomas G. Williams", email = "thomas.williams@physics.ox.ac.uk"},
]
maintainers = [
    {name = "Thomas G. Williams", email = "thomas.williams@physics.ox.ac.uk"},
]

classifiers = [
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 5 - Production/Stable",

  # License
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",

  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
    "astropy == 7.2.0",
    "astropy-healpix == 1.1.3",
    "astroquery == 0.4.11",
    "cmocean == 4.0.3",
    "crds == 13.2.3",
    "gwcs == 1.0.3",
    "image-registration == 0.2.9",
    "jwst == 2.0.1",
    "lmfit == 1.3.4",
    "matplotlib == 3.10.8",
    "numpy == 2.2.6",
    "opencv-python-headless == 4.13.0.92",
    "photutils == 2.3.0",
    "pyerfa == 2.0.1.5",
    "pypdf == 6.12.2",
    "pysiaf == 0.25.0",
    "pytest == 9.0.3",
    "reproject == 0.19.0",
    "requests == 2.34.2",
    "scikit-image == 0.26.0",
    "scipy == 1.17.1",
    "shapely == 2.1.2",
    "spherical-geometry == 1.4.0",
    "setuptools == 82.0.1",
    "stdatamodels == 5.0.2",
    "stsci.imagestats == 1.8.4",
    "stsci.stimage == 0.3.0",
    "stpsf == 2.2.0",
    "stwcs == 1.7.7",
    "synphot == 1.7.0",
#    "spacepylot@git+https://github.com/ejwatkins-astro/spacepylot.git",
    "threadpoolctl == 3.6.0",
    "tomli == 2.4.1",
    "tqdm == 4.67.3",
    "tweakwcs == 0.9.0",
]

[project.optional-dependencies]
docs = [
    "sphinx-automodapi == 0.22.0",
    "sphinx-rtd-theme == 3.1.0",
]

[project.urls]
"Homepage" = "http://phangs.org"
"Bug Reports" = "https://github.com/phangsTeam/pjpipe/issues"
"Source" = "https://github.com/phangsTeam/pjpipe"

[tool.setuptools.packages.find]
exclude = ["LEGACY/*"]

[build-system]
requires = [
    "setuptools == 82.0.1",
    "wheel == 0.46.3",
    "setuptools_scm == 10.0.5",
]
build-backend = "setuptools.build_meta"
