crds_path = '/Users/thomaswilliams/Documents/phangs/jwst/crds/'
crds_context = 'jwst_1238.pmap'
raw_dir = '/Users/thomaswilliams/Documents/phangs/jwst/jwst_raw/3707/'
reprocess_dir = '/Users/thomaswilliams/Documents/phangs/jwst_3707/reprocessing/'
alignment_dir = '/Users/thomaswilliams/PycharmProjects/pjpipe/config/3707/alignment/'
webb_psf_data = '/Users/thomaswilliams/Documents/phangs/jwst/webb_psf_data/'
processors = 4
