crds_path = '/Users/thomaswilliams/Documents/phangs/jwst/crds/'
raw_dir = '/Users/thomaswilliams/Documents/phangs/jwst/jwst_raw/archive_20240402'
reprocess_dir = '/Users/thomaswilliams/Documents/phangs/jwst/jwst_phangs_reprocessed/'
alignment_dir = '/Users/thomaswilliams/PycharmProjects/pjpipe/config/2107/alignment/2107/alignment/'
webb_psf_data = '/Users/thomaswilliams/Documents/phangs/jwst/webb_psf_data/'
