[projects.2107]
targets = [
    'ic5332',
    'ngc0628',
    'ngc1087',
    'ngc1300',
    'ngc1365',
    'ngc1385',
    'ngc1433',
    'ngc1512',
    'ngc1566',
    'ngc1672',
    'ngc2835',
    'ngc3351',
    'ngc3627',
    'ngc4303',
    'ngc4321',
    'ngc4535',
    'ngc5068',
    'ngc7496',
]

[pipeline]

data_version = 'v0p8'
nircam_bands = [
    'F300M',
]
miri_bands = [
    'F770W',
]

group_tweakreg_dithers = [
    'nircam',
    'miri',
]

[lv3_parameters.tweakreg]

align_to_gaia = false
brightest = 500
snr_threshold = 3
expand_refcat = true
fitgeometry = 'shift'
minobj = 3
peakmax.nircam = 20
roundlo.nircam = -0.5
roundhi.nircam = 0.5

# Parameters to get wcs_adjust shifts
searchrad = 2
separation.miri = 1
tolerance.miri = 0.7
separation.nircam = 2
tolerance.nircam = 1
use2dhist = true
nclip = 5

# Tweak boxsize, so we detect objects in diffuse emission
bkg_boxsize.nircam_short = 100
bkg_boxsize.nircam_long = 100
bkg_boxsize.miri = 25
enforce_user_order = true
