name: Build Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  job:
    name: Build Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Versions listed at https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: ["3.9",
                         "3.10",
                         "3.11",
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build